# --------------------- #
#    Generation File    #
# --------------------- #

imports = [
  "important",
  "terminal",
  "fonts",
  "xorg",
  "xorg-extra",
  "wayland",
  "hyprland",
  "languages",
  "graphical",
  "misc-apps",
  "capture",
]

[managers.system]
items = [
]

[managers.flatpak]
items = [
  # "org.polymc.PolyMC"
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
]
